services:
  - type: web
    name: booking-api
    runtime: node
    plan: starter
    branch: main
    buildCommand: "npm ci"
    startCommand: "node server.js"
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: booking-db
          property: connectionString
      - key: DATABASE_SSL
        value: "true"

databases:
  - name: booking-db
